services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATADIR: /var/lib/postgresql/data
    command: >
      postgres
        -c custom.versioning=${VERSIONING:-0}
        -c custom.authorization=${AUTHORIZATION:-0}
        -c custom.duplicates=${DUPLICATES:-0}
        -c custom.epsg=${EPSG:-4326}
        -c custom.user=${ISTSOS_ADMIN:-admin}
        -c custom.password=${ISTSOS_ADMIN_PASSWORD:-admin}
        -c log_statement="all"
        -c log_destination="stderr"
        -c log_duration="on"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - v-istsos4-database-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      HOSTNAME: ${HOSTNAME}
      SUBPATH: ${SUBPATH}
      VERSION: ${VERSION}
      DEBUG: ${DEBUG}
      VERSIONING: ${VERSIONING}
      POSTGRES_DB: ${POSTGRES_DB}
      ISTSOS_ADMIN: ${ISTSOS_ADMIN}
      ISTSOS_ADMIN_PASSWORD: ${ISTSOS_ADMIN_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PG_MAX_OVERFLOW: ${PG_MAX_OVERFLOW}
      PG_POOL_SIZE: ${PG_POOL_SIZE}
      PG_POOL_TIMEOUT: ${PG_POOL_TIMEOUT}
      COUNT_MODE: ${COUNT_MODE}
      COUNT_ESTIMATE_THRESHOLD: ${COUNT_ESTIMATE_THRESHOLD}
      TOP_VALUE: ${TOP_VALUE}
      PARTITION_CHUNK: ${PARTITION_CHUNK}
      REDIS: ${REDIS}
      EPSG: ${EPSG}
      AUTHORIZATION: ${AUTHORIZATION}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      ANONYMOUS_VIEWER: ${ANONYMOUS_VIEWER}
    command: uvicorn --reload --host 0.0.0.0 --port 5000 app.main:app
    ports:
      - ${EXTERNAL_PORT}:5000
    volumes:
      - ./api/app:/code/app
    working_dir: /code

  redis:
    image: redis:7.4.0-alpine3.20
    restart: always
    volumes:
      - v-istsos4-redis-data:/data

  dummy_data:
    build:
      context: ./dummy_data
      dockerfile: Dockerfile
    environment:
      HOSTNAME: ${HOSTNAME}
      SUBPATH: ${SUBPATH}
      VERSION: ${VERSION}
      VERSIONING: ${VERSIONING}
      POSTGRES_DB: ${POSTGRES_DB}
      ISTSOS_ADMIN: ${ISTSOS_ADMIN}
      ISTSOS_ADMIN_PASSWORD: ${ISTSOS_ADMIN_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DUMMY_DATA: ${DUMMY_DATA}
      CLEAR_DATA: ${CLEAR_DATA}
      N_THINGS: ${N_THINGS}
      N_OBSERVED_PROPERTIES: ${N_OBSERVED_PROPERTIES}
      INTERVAL: ${INTERVAL}
      FREQUENCY: ${FREQUENCY}
      START_DATETIME: ${START_DATETIME}
      CHUNK_INTERVAL: ${CHUNK_INTERVAL}
      EPSG: ${EPSG}
      AUTHORIZATION: ${AUTHORIZATION}
    command: python3 generator.py
    volumes:
      - ./dummy_data:/dummy_data
    working_dir: /dummy_data
    depends_on:
      database:
        condition: service_healthy

  docs:
    build:
      context: ./docs/mkdocs
      dockerfile: dockerfile
    ports:
      - 8019:8000
    volumes:
      - ./docs/mkdocs:/docs
# You might need to run `sudo chown -R $USER schemaspy/` to fix permissions
# schemaspy:
#   image: schemaspy/schemaspy:6.2.4
#   volumes:
#     - ./database/schemaspy/sensorthings_history:/output
#   command: [ "-t", "pgsql11", "-db", "istsos", "-host", "database", "-port", "5432", "-s", "sensorthings_history", "-u", "postgres", "-p", "postgres", "-vizjs" ]
#   depends_on:
#     - database

volumes:
  v-istsos4-database-data:
    name: v-istsos4-database-data
  v-istsos4-redis-data:
    name: v-istsos4-redis-data
