site_name: istSOS4
site_author: "istSOS4 Things"
site_url: https://ord.supsi.ch/

repo_name: "GitLab"
repo_url: "https://gitlab.com/geo-ord/osires_code"
docs_dir: "docs"
theme:
  name: "material"
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/istsos_bars_white.png
  font:
    text: Ubuntu
  palette:
    scheme: istsos
  extra_css:
    - extra.css
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - content.code.copy

nav:
  - Tutorial:
      - Welcome to the istSOS4-Things tutorial: tutorial/tutorial_index.md
      - Understanding the Principles and Functionality of istSOS4: tutorial/intro.md
      - Installing and Configuring istSOS4: tutorial/install.md
      - Managing Authentication & Authorization:
          - Concepts and Theory: tutorial/authorization.md
          - Hands-On Example (Python): tutorial/authorization_notebook.ipynb
      - Utilizing the SensorThings API:
          - Register Entities: tutorial/sta_entity.ipynb
          - Register Observations: tutorial/sta_observation.ipynb
      - Leveraging the TravelTime Extension for Reproducibility and Data Lineage: tutorial/traveltime.ipynb
      - Utilizing Python for Data Curation and Quality: tutorial/quality.ipynb
      - Applying Advanced Filtering Techniques for Data Retrieval: tutorial/filtering.ipynb
      - Applying Machine Learning and AI for Time Series Data Processing: tutorial/ai.ipynb
  - Team: team.md

extra_css:
  - assets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-jupyter