{
    "istsos_url": "http://localhost:8018/istsos4/v1.1",
    "istsos_username": "sensor1",
    "istsos_password": "<REDACTED>",
    "dry_run": False,
    "log_file": "logs/ftp2istsos4.log",
    "log_level": "INFO",
    "log_max_bytes": 5242880,
    "log_backup_count": 5,
    "source_log_dir": "logs/sources",
    "ftps": [
        {
            "type": "ufam",  # vulink, ufam, vulink-varese
            "host": "ftp.hydrodata.ch",
            "port": 22,
            "username": "SUPSI-IST",
            "password": "<REDACTED>",
            "protocol": "sftp",
            "key_path": "/home/daniele/.ssh/bafu_id_rsa",
            "remote-dir": "/CSV",
            "files": [
                {

                    "file_path": "2074/BAFU_2074_PegelDrucksonde.csv",
                    "columns": [
                        {
                            "idx": 0,
                            "type": "datetime",
                            "format": "%Y-%m-%d %H:%M:%S"
                        },
                        {
                            "idx": 1,
                            "type": "float",
                            "name": "dTEST"
                        }
                    ]
                }
            ]
        },
    #     {
    #         "type": "vulink-varese",
    #         "host": "ftpusers.arpalombardia.it",
    #         "port": 21,
    #         "username": "DATIBOEVA1",
    #         "password": "<REDACTED>",
    #         "protocol": "ftp",
    #         "remote-dir": "/DATIBOEVA1/varese",
    #         "tz": "Europe/Rome",
    #         "files": [
    #             {
    #                 "filename_suffix": "BoaVarese-MeteoMTX.txt",
    #                 "columns": [
    #                     {
    #                         "idx": 0,
    #                         "type": "datetime",
    #                         "format": "%Y-%m-%dT%H:%M:%S%z"
    #                     },
    #                     {
    #                         "idx": 1,
    #                         "type": "float",
    #                         "name": "AirPressure_VA"
    #                     },
    #                     {
    #                         "idx": 2,
    #                         "type": "float",
    #                         "name": "PAR_VA"
    #                     },
    #                     {
    #                         "idx": 3,
    #                         "type": "float",
    #                         "name": "SolarRad_VA"
    #                     },
    #                     {
    #                         "idx": 4,
    #                         "type": "float",
    #                         "name": "AirHum_VA"
    #                     },
    #                     {
    #                         "idx": 5,
    #                         "type": "float",
    #                         "name": "AirTemp_VA"
    #                     },
    #                     {
    #                         "idx": 6,
    #                         "type": "float",
    #                         "name": "AirTemp_VA"
    #                     },
    #                     {
    #                         "idx": 7,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0100cm_C3"
    #                     }
    #                 ]
    #             },
    #             {
    #                 "filename_suffix": "BoaVarese-Termistori.txt",
    #                 "columns": [
    #                     {
    #                         "idx": 0,
    #                         "type": "datetime",
    #                         "format": "%Y-%m-%dT%H:%M:%S%z"
    #                     },
    #                     {
    #                         "idx": 1,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0100cm"
    #                     },
    #                     {
    #                         "idx": 2,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0200cm"
    #                     },
    #                     {
    #                         "idx": 3,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0300cm"
    #                     },
    #                     {
    #                         "idx": 4,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0400cm"
    #                     },
    #                     {
    #                         "idx": 5,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0500cm"
    #                     },
    #                     {
    #                         "idx": 6,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0700cm"
    #                     },
    #                     {
    #                         "idx": 7,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0900cm"
    #                     },
    #                     {
    #                         "idx": 8,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z1100cm"
    #                     },
    #                     {
    #                         "idx": 9,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z1300cm"
    #                     },
    #                     {
    #                         "idx": 10,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z1500cm"
    #                     },
    #                     {
    #                         "idx": 11,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z1700cm"
    #                     },
    #                     {
    #                         "idx": 12,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z1900cm"
    #                     },
    #                     {
    #                         "idx": 13,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z2100cm"
    #                     },
    #                     {
    #                         "idx": 14,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z2300cm"
    #                     },
    #                     {
    #                         "idx": 15,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z2500cm"
    #                     }
    #                 ]
    #             },
    #             {
    #                 "filename_suffix": "BoaVarese-AT500.txt",
    #                 "columns": [
    #                     {
    #                         "idx": 0,
    #                         "type": "datetime",
    #                         "format": "%Y-%m-%dT%H:%M:%S%z"
    #                     },
    #                     {
    #                         "idx": 1,
    #                         "type": "float",
    #                         "name": "Chl_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 2,
    #                         "type": "float",
    #                         "name": "PC_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 3,
    #                         "type": "float",
    #                         "name": "PE_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 4,
    #                         "type": "float",
    #                         "name": "Cond20_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 5,
    #                         "type": "float",
    #                         "name": "O2C_VA_z0300cm"
    #                     },
    #                     {
    #                         "idx": 6,
    #                         "type": "float",
    #                         "name": "O2C_VA_z0100cm"
    #                     },
    #                     {
    #                         "idx": 7,
    #                         "type": "float",
    #                         "name": "O2S_VA_z0300cm"
    #                     },
    #                     {
    #                         "idx": 8,
    #                         "type": "float",
    #                         "name": "O2S_VA_z0100cm"
    #                     },
    #                     {
    #                         "idx": 9,
    #                         "type": "float",
    #                         "name": "Chl_RFU_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 10,
    #                         "type": "float",
    #                         "name": "PC_RFU_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 11,
    #                         "type": "float",
    #                         "name": "PE_RFU_VA_z020cm"
    #                     },
    #                     {
    #                         "idx": 12,
    #                         "type": "float",
    #                         "name": "ORP_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 13,
    #                         "type": "float",
    #                         "name": "WaterTemp_VA_z0020cm"
    #                     },
    #                     {
    #                         "idx": 14,
    #                         "type": "float",
    #                         "name": "pH_VA_z0020cm"
    #                     }
    #                 ]
    #             }
    #         ]
    #     }
    ]
}
